version: '3.7'
services:
  web:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    image: server:latest
    volumes:
      - workspace:/var/lib/server
    ports:
    - 8070-8079:8080
    depends_on:
    - db
  db:
    container_name: book_db
    image: postgres:11.1
    volumes:
    - workspace:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=1111
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432

volumes:
  workspace:
